---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codekernel-wildcard-certificate
  namespace: kube-system
spec:
  dnsNames:
    - codekernel.co.uk
    - "*.codekernel.co.uk"
  secretName: codekernel-wildcard-certificate
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer