---
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-dns
data:
  access-token: "{{ do_access_token_base64 }}"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: "{{ email_address }}"
    server: "https://acme-v02.api.letsencrypt.org/directory"  # https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - dns01:
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token