---
# Source: authelia/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-service
  namespace: vaultwarden
spec:
  type: ClusterIP
  sessionAffinity: None
  selector:
    name: vaultwarden
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
