---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: archivebox-pvc
  namespace: archivebox
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi