---
- name: Create Cert Manager namespace
  kubernetes.core.k8s:
    name: cert-manager
    api_version: v1
    kind: Namespace
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"

- name: Install cert-manager
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    template: cert-manager.yml
    namespace: cert-manager

- name: Waiting for cert-manager to be deployed
  kubernetes.core.k8s_info:
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    kind: Deployment
    wait: true
    name: "{{ item }}"
    namespace: cert-manager
    wait_sleep: 10
    wait_timeout: 360
  with_items:
    - cert-manager
    - cert-manager-cainjector
    - cert-manager-webhook

- name: Setup DigitalOcean DNS issuer
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    template: digitalocean-dns.yml
    namespace: cert-manager

- name: Create wildcard certificate
  kubernetes.core.k8s:
    state: present
    kubeconfig: "/home/{{ ansible_user }}/.kube/config"
    template: digitalocean-wildcard.yml
    namespace: cert-manager
