---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-persistent
  namespace: monitoring
spec:
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
        - node-exporter
        - longhorn-prometheus-servicemonitor
        - kube-state-metrics
        - kubelet
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
  retention: 4w
  retentionSize: 30GiB
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        resources:
          requests:
            storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-persistent
  namespace: monitoring
spec:
  type: ClusterIP
  ports:
  - name: web
    port: 9090
    targetPort: 9090
  selector:
    prometheus: prometheus-persistent
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prometheus-ingress
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/whitelist-source-range: "192.168.56.0/21,192.168.65.0/24"
spec:
  rules:
  - host: prometheus.codekernel.co.uk
    http:
      paths:
      - backend:
          service:
            name: prometheus-persistent
            port:
              number: 9090
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - prometheus.codekernel.co.uk
