---
# Source: drone/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone
  namespace: drone
  labels:
    release: drone
    helm.sh/chart: drone-0.6.1
    app.kubernetes.io/name: drone
    app.kubernetes.io/instance: drone
    app.kubernetes.io/component: server
    app.kubernetes.io/version: "2.12.1"
    app.kubernetes.io/managed-by: Helm
data:

  DRONE_GITEA_SERVER: "https://git.codekernel.co.uk"
  DRONE_GIT_ALWAYS_AUTH: "true"
  DRONE_SERVER_HOST: "drone.codekernel.co.uk"
  DRONE_SERVER_PROTO: "https"