---
apiVersion: v1
kind: ConfigMap
metadata:
  name: drone-config
  namespace: drone
  labels:
    app: drone
data:
  DRONE_GITEA_SERVER: https://git.codekernel.co.uk
  DRONE_GIT_ALWAYS_AUTH: true
  DRONE_SERVER_HOST: drone.codekernel.co.uk
  DRONE_SERVER_PROTO: https
