---
# Source: drone/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone
  labels:
    release: drone
    helm.sh/chart: drone-0.6.1
    app.kubernetes.io/name: drone
    app.kubernetes.io/instance: drone
    app.kubernetes.io/component: server
    app.kubernetes.io/version: "2.12.1"
    app.kubernetes.io/managed-by: Helm