---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: drone-ingress
  namespace: drone
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: drone.codekernel.co.uk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: drone
            port:
              number: 3000
  tls:
  - hosts:
    - drone.codekernel.co.uk
