---
# Source: drone-runner-kube/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner-kube
  labels:
    helm.sh/chart: drone-runner-kube-0.1.10
    app.kubernetes.io/name: drone-runner-kube
    app.kubernetes.io/instance: drone-runner-kube
    app.kubernetes.io/component: drone-runner-kube
    app.kubernetes.io/version: "1.0.0-rc.3"
    app.kubernetes.io/managed-by: Helm
---
# Source: drone-runner-kube/templates/rbac.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner-kube
  namespace: "drone-build"
  labels:
    helm.sh/chart: drone-runner-kube-0.1.10
    app.kubernetes.io/name: drone-runner-kube
    app.kubernetes.io/instance: drone-runner-kube
    app.kubernetes.io/component: drone-runner-kube
    app.kubernetes.io/version: "1.0.0-rc.3"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - create
      - delete
      - list
      - watch
      - update
---
# Source: drone-runner-kube/templates/rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone-runner-kube
  namespace: "drone-build"
  labels:
    helm.sh/chart: drone-runner-kube-0.1.10
    app.kubernetes.io/name: drone-runner-kube
    app.kubernetes.io/instance: drone-runner-kube
    app.kubernetes.io/component: drone-runner-kube
    app.kubernetes.io/version: "1.0.0-rc.3"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: drone-runner-kube
    namespace: drone
roleRef:
  kind: Role
  name: drone-runner-kube
  apiGroup: rbac.authorization.k8s.io