---
# Source: drone-runner-docker/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-runner-docker
  labels:
    release: drone-runner-docker
    helm.sh/chart: drone-runner-docker-0.4.0
    app.kubernetes.io/name: drone-runner-docker
    app.kubernetes.io/instance: drone-runner-docker
    app.kubernetes.io/version: "1.8.1"
    app.kubernetes.io/managed-by: Helm