apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-runner-secret
  namespace: drone
spec:
  encryptedData:
    DRONE_RPC_SECRET: AgBgu75tZR1ma+MjiLvQyfUyTOox2tzB1x8LnwBNA8q0bM59qj8bxiA/l4DzX7Yj5zPu/kSH89raw2AjL/e9WiJHsDKn5yaxfbdZ1Kcch/XuYV9ao0DFMAjDz7YQ67DvHI9NdV5l5tdYSWBD4BbWcfLZvem/2k12sBVQdJ6euQiHAnDpfVZKbFs/7pONMAbYNq1DrKMPn00p/lgQ0GXh6uw82Lkl3U/jjewb9IPRerAsbxDNtMBKb8rOlZ5Fz6HdJ3wGEx9mdCerNvtNWkyIxQcD+9x6ly8kDuw8XhEjsqrgidd1BY1pXD+B4mHo5YYMuoNHtLZtBeH2OsS6GSauMMpzve6yoYIg/7P6lPcoQosUAr5u9IxxziIXF7kdQeBVgHFmMbJJSSHjtI5XdtJRiKliCP/APs0T5/Fi82eiVY72Kq81IXc0DS8y36wsK9G2MDG3r79ffyKg4gOHbAskAPc6H7bQDLhibvmH18y0KdNBMxqXIpHaL7Z6pGW4kQjoXaxqobm1hXRSmuKovvqNPZq9aGOV0fAvSbhN0nZNQUXHAK3uRS+Oplb0F0m1vnBAg/8B0F9VGAQernny/hKMw8Wu/4mSHtxi+p/Ln1EwI9iqoC5Zt8j39/HdCxz9MMkSE+d/g++on1dE5UWaZ0Agnw9sQsE1KM6ZeWNwjTwZRQWUttauRiNEYrdfh3gSisLc7fPKT81yhQGWgSHdbuAvRu1ZdsxWfpyfFyqtN1Z/4a4JOg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: drone-runner-secret
      namespace: drone

