apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-runner-secret
  namespace: drone
spec:
  encryptedData:
    DRONE_RPC_SECRET: AgBgwhdPvOaRv3tMxGhhrDdZ83jZBU5pXn7+tD5kzDOI6lfiY0QcCuUekdByEITsCUYGburTkFXv2CZYG8UUWIvtvlK2rUilrvNkPLnwDKNhYuiicy6JrHUOIBW6lyCn/kvWY40e1SMh2OeMAYcLCvy5fUUOwDJ4KUz3HS9M1LUHOWlNv/AhF3wggdQIZVF6mJWdqu2FtH7Xl8/zvp5Cq7jE4s10+VtOBdMSe4cFz4HsxePy6H/9ecCD7NLfg84Kzf3JQDYHt+rcFCeEhp2zobK4sPBQFQsOUtfuyoxURdsnjLoGbRmp1ZliXFt30hk/aJcbKQj/HimIN0559YBhCm8QkBvNLuk+jZWf0Vlb5tj95/Uny1sRUp05x74NPqn4OXqkpY24NXTg7+u4uLSDHOoC73LJHblRrf8UAaH10noPL8eNJ1OEBcImmfzTmefRPY0b/PIS6yecLAEgIA19W7WGXJpktVlnXrfsATH79fKbzBRHHvQfa3p348F6UQ0kFhnqulqrQXAzbVgy2UoBy1NO5e46d0aNyt4FWJzrM0QjlJUNcmomVG2l807xBkt9SBJ3juWd+VdAmr2ztA2t0FuyMnfpalZJpiBIYiOFaxJMUQy1Vz86skxiiM9mSwax2HxVcDdPgIvod+j4If5rdKnUDn6tQHbAWlBGei1BhDPirrFPhUFy7KhSAC7Ho2nRaNJPKLfK43CKiBgobDzBJKMCl74IghzpUBIm/SP58Va+2w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: drone-runner-secret
      namespace: drone

