apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: drone-runner-secret
  namespace: drone
spec:
  encryptedData:
    DRONE_RPC_SECRET: AgDNF8ZqyFyjPrb1ZeDHB7CWi+aA1c8ZR384gov/V00gAIdcNZgRpcHJlzY5MrXigYjTuoVIa9jdzs2bVU+D2xDzpFg/ZVUIiA5c1IUqRlVC2rkefdqdT18l/bIl5EFEBOdHE2eegMxEKbUjIbnTVr3vZHm5rYklsksJldAdkFrOjNfhcoHmHLGVXF6SSLd4XE13O2269/U0cK0vZ20/u+9174fAP3BNTLC0JvSfbLOITFTNZ9CnT2GM6EaUOYcn4pPrtRj/ua6YJ9I8ocofW3aSm5MEMKFvMnQJKX2NqMqhCAyKXHQmJzWGciJYjj0QCgTvdzHu3iWxzvU3knQwqd8q7d3u62BD7qGYZYd68mOSILSlFPGbQ4qaZxmNoKMaSWPec9TlymKGWgaU2OcoyLDpkCIwSMJQsTkmyl4HJWe2x//bxY8OKHjUKzcR6ebKSXFfM60AjFiOQZnh1mNKaKopYC8JvBtUD3VZpHk1QPToMWAcoJ44WPjtyH1UoLi9P9h1sTspHVsJ8FXzIXvynT89WTxoo+KX1bTbeJJMC02kP6grgLhOYxz7RAv7uNL2O5EKhIPaAm9/fUpwRrzjJtI17+jbIX9TIXy6z6mCItbs7fVvHIIgM97OjvRrl/pr7CxEc46hqs2MCzdgjA2TosP00xo4+r3YylEgDqJfmlHu8mUFkkG9Dik1rAVYzmwuHxrRiSAL4TAOoif4ow4bospRX5FxJxLQw6Ly4KOVLy/YDQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: drone-runner-secret
      namespace: drone

