---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gotify-config
  namespace: gotify
data:
  GOTIFY_SERVER_PORT: "80"
  GOTIFY_SERVER_SSL_ENABLED: "false"
  GOTIFY_DATABASE_DIALECT: "sqlite3"
  GOTIFY_DATABASE_CONNECTION: "data/gotify"
  GOTIFY_REGISTRATION: "false"
