apiVersion: v1
kind: Secret
metadata:
  name: backup-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: VXNuanl4WmRVYlUxNjFobg==
  AWS_SECRET_ACCESS_KEY: bGxndmV6Q3VnNGYxc2l1dEZtM0VrRzRMdzZlMm5pNHE=
  AWS_ENDPOINTS: aHR0cDovLzE5Mi4xNjguNTcuMjo5MDAw
