---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authelia-pvc
  namespace: authelia
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi