---
# Source: authelia/templates/configMap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  namespace: authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.36.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.38
data:
  configuration.yaml: |
    ---
    theme: dark
    default_redirection_url: https://codekernel.co.uk
    default_2fa_method: ""
    server:
      host: 0.0.0.0
      port: 9091
      asset_path: ""
      headers:
        csp_template: ""
      read_buffer_size: 4096
      write_buffer_size: 4096
      enable_pprof: false
      enable_expvars: false
    log:
      level: info
      format: text
      file_path: ""
      keep_stdout: true
    totp:
      disable: false
      issuer: codekernel.co.uk
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1
      secret_size: 32
    webauthn:
      disable: false
      display_name: Authelia
      attestation_conveyance_preference: indirect
      user_verification: preferred
      timeout: 60s
    ntp:
      address: time.cloudflare.com:123
      version: 4
      max_desync: 3s
      disable_startup_check: false
      disable_failure: false
    authentication_backend:
      password_reset:
        disable: false
        custom_url: ""
      file:
        path: /config/users_database.yml
        password: 
          algorithm: sha512
          iterations: 100000
          key_length: 32
          memory: 1024
          parallelism: 8
          salt_length: 16
    password_policy:
      standard:
        enabled: false
        min_length: 8
        max_length: 0
        require_uppercase: true
        require_lowercase: true
        require_number: true
        require_special: true
      zxcvbn:
        enabled: false
        min_score: 0
    session:
      name: authelia_session
      domain: codekernel.co.uk
      same_site: lax
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
    regulation: 
      ban_time: 5m
      find_time: 2m
      max_retries: 3
    storage:
      local:
        path: /config/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /config/notification.txt
    access_control:
      default_policy: deny
      networks: 
      - name: private
        networks:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
      - name: vpn
        networks:
        - 192.168.64.0/24
        - 192.168.65.0/24
      rules:
        - policy: bypass
          domain:
            - 'codekernel.com'
        - policy: one_factor
          domain:
            - 'snippets.codekernel.co.uk'
    ...