---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  namespace: authelia
  labels:
    app.kubernetes.io/name: authelia
    app.kubernetes.io/instance: authelia
    app.kubernetes.io/version: 4.36.1
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: authelia-0.8.38
data:
  configuration.yaml: |
    ---
    theme: dark
    default_redirection_url: https://codekernel.co.uk
    default_2fa_method: ""
    server:
      address: "tcp://:9091"
      path: ""
      asset_path: "/config/assets/"
      disable_healthcheck: false
      headers:
        csp_template: ""
      buffers:
        read: 4096
        write: 4096
      timeouts:
        read: "6s"
        write: "6s"
        idle: "30s"
    log:
      level: info
      format: text
      file_path: ""
      keep_stdout: true
    telemetry:
      metrics:
        enabled: true
        address: "tcp://:9959"
        buffers:
          read: 4096
          write: 4096
        timeouts:
          read: 6s
          write: 6s
          idle: 30s
    totp:
      disable: false
      issuer: codekernel.co.uk
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1
      secret_size: 32
    webauthn:
      disable: true
    ntp:
      address: time.cloudflare.com:123
      version: 4
      max_desync: 3s
      disable_startup_check: false
      disable_failure: false
    authentication_backend:
      password_reset:
        disable: true
        custom_url: ""
      refresh_interval: "always"
      file:
        path: /users_database.yml
        watch: true
        password: 
          algorithm: sha512
          iterations: 100000
          key_length: 32
          memory: 1024
          parallelism: 8
          salt_length: 16
    password_policy:
      standard:
        enabled: true
        min_length: 8
        max_length: 0
        require_uppercase: true
        require_lowercase: true
        require_number: true
        require_special: false
      zxcvbn:
        enabled: false
        min_score: 0
    privacy_policy:
      enabled: false
    session:
      name: authelia_session
      domain: codekernel.co.uk
      same_site: lax
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
      redis:
        host: redis.authelia.svc.cluster.local
        port: 6379
        database_index: 0
    regulation: 
      ban_time: 5m
      find_time: 2m
      max_retries: 3
    storage:
      local:
        path: /config/db.sqlite3
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /config/notification.txt
    access_control:
      default_policy: deny
      networks: 
      - name: private
        networks:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
      - name: vpn
        networks:
          - 192.168.64.0/24
          - 192.168.65.0/24
      - name: home
        networks:
          - 192.168.56.0/24
          - 192.168.57.0/24
          - 192.168.58.0/24
          - 192.168.59.0/24
      rules:
        # Protect the vaultwarden admin routes
        - policy: one_factor
          domain: 'vaultwarden.codekernel.co.uk'
          resources:
            - "^*/admin.*$"
        ## Bypass the following domains externally
        - policy: bypass
          domain: 
            # Authelia - required
            - 'auth.codekernel.co.uk'
            # Dashboard - default redirect
            - 'codekernel.co.uk'
            # Git - own authentication
            - 'git.codekernel.co.uk'
            # Drone - uses git authentication
            - 'drone.codekernel.co.uk'
            # Nextcloud - own authentication
            - 'nextcloud.codekernel.co.uk'
            # Vaultwarden - own auth - but no admin route
            - 'vaultwarden.codekernel.co.uk'
        - policy: bypass
          domain:
            - rancher.codekernel.co.uk
            - longhorn.codekernel.co.uk
          networks:
            - vpn
            - home
        - policy: bypass
          domain: 'dash.codekernel.co.uk'
          networks:
            - private
            - vpn
  users_database.yml: |
    # yamllint disable rule:line-length
    ---
    ###############################################################
    #                         Users Database                      #
    ###############################################################
    users:
      ethan:
        displayname: "Ethan Cotterell"
        email: "ethancotterell@gmail.com"
        password: "$argon2id$v=19$m=65536,t=3,p=4$UXNNN1F4M1M4VWFtcHZnaQ$o2wtG+gJ1/+n+ee4TLr3iDgrK+iTu0VQDoy1iXGWH7M"
        groups:
          - admin
          - dev
      tom:
        displayname: "Tom"
        email: "tom@awencollective.com"
        password: "$argon2id$v=19$m=65536,t=3,p=4$appuDmT5MjKzK/5+EhkcQw$slkSJcAIuMqf6+7XjYIwfaqu3l0ixh2d53k3pecAOAk" 
        groups:
          - dev
    ...
    # yamllint enable rule:line-length