---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanboard-pvc
  namespace: kanboard
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi