---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snippets-pvc
  namespace: snippets
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
