apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: mycustomkeys
  namespace: kube-system
  labels:
    sealedsecrets.bitnami.com/sealed-secrets-key: active
data:
  tls.crt: "{{ sealed_secrets_crt }}"
  tls.key: "{{ sealed_secrets_key }}"
