---

- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
    cache_valid_time: 3600

- name: Upgrade packages
  ansible.builtin.apt:
    upgrade: "dist"
    force_apt_get: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: "present"
  with_items: "{{ packages }}"

- name: Install pip dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items: "{{ pip_packages }}"
