---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-persistent
  namespace: monitoring
spec:
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus
  serviceMonitorSelector:
    matchExpressions:
    - key: name
      operator: In
      values:
        - node-exporter
        - longhorn-prometheus-servicemonitor
        - kube-state-metrics
        - kubelet
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: true
  retention: 4w
  retentionSize: 30GiB
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: longhorn
        resources:
          requests:
            storage: 40Gi