apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgA+ukPaxcJusIiPiX1ZrUA4FoaJ9PkRpGHg9SagvM6TI90KXKcnk7VwasvO6O9qWG7M5ZAfGfgoOv2jrCYS2rG4pvGhYaqb8ks4fJfI5qJ/IqRO51DsfIfDXYSxb2GTLJA//uuMP1PAo3QGUVDAX3Q56guuV4tjVEKHSk26y6mQpEBNHuprqOBWilfXWj/0zD+TMVFFxojWDX6BCvGF15a1ZLYjFIqKRHNPJx+J6YTgJ+4qhzrWfwpI/wvtja0e2pqSO2WzudcOIiME9znZS+1tLMJ9R1jjvuTDBOpvfR6Z5FpKnMrzSr57XOip4Q0gL8e/eX2hn7I8/DKjCaYtFc6+MKi2J99SVYoXOrWSM8TFkGaFxGdohG3+FxRZdqYRn8HVJWUjo1HbZ+GoDFJjTXGbkwFBZZ+EKP5D5eKLOZGfVFJcDBmPwlrVRsLj7c01XSQfn2nGDMCWGQKoQvJto9jwmmGcOpJR3P1Qi5zhKRslDJZKYAJIQ58D+PjdId8QemzGRc2lRh2ciT9+EHvzfl9kyGOHbt+vacRTW4vrE/mynsBUudYI6QUkNsBNIZzG8d/GFQNi30MPB8mR642ZWHLmszM0m85UWXswnMji7tn7bP8xCHdzZK0Ww2ssmhJ/DI+e+lNHoCkqyIDjP1EvRw/qaZyz/PkVgI0eXsznjyOjNLv6t67MVkmOgYXjpK6BkSQsxEzbPD9frLQEctiaquSRQ0o4aaD8ZLWE1AcSkQ0x5w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: nextcloud

