---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: nextcloud
  labels:
    app: mariadb
data:
  MYSQL_DATABASE: "nextcloud"
  MYSQL_USER: "nextcloud"
  PUID: "1000"
  PGID: "1000"
  TZ: "Europe/London"