apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBn+sk2iWJ0oG4BWnpiFgOnIIPvaJn4MLq01fXsPByABIugVc2+eo7+iThsfN+xZTpGGHRoUTKLLhhADEeVOi6K2t82qyaal79P1VdOeHDK21VJBgPSG61AcdyfvPhn29945ZYNRXBa+sovrdmtS4v88D5pnI/IKTqCz6ET25HEDE1O3xXJEs+cXd2QxaZNvOqFDwdC4gCsZQqoaoNT9AVasHeWyGj8bdKPGLuULakaRqkTyaw3g/5f++6PFq807iRMzmNpDpGuXp9zCu39XjDObOYpHg7ECpmSK3tahQv0SW58PdJPyhaK8MmaH2/C59nbniU6nKwmO5Zwj0Fjyxg3GM8NXtfiBwGKpeg3aqZQ21oE0SqtHJMOChHgI+4uozd0o0R+fLZCjRz3JU47rrSj0XPEgVg3xv+LtyaWcPPVH1fBaINblVv+6ZVrkqze35vIqUlpHLpvQRFEDyRgtKlFZwYS+fjfP3Zo/JEsOA6np0h/idn0EC0r3ASOue0UOwa2Pl5O3uSwiPIJVvXjvR+fdi60duh6q7t1mWWR5xOTpiAM+Qm+W8HIH3b8xeEO2cvgDRPKizdMUCJ13FssMlyIalwk4Aw6SZWEhbZ+Bcva73R+DlHHoxpoVj/d2bEzBScjRYdMeNqhQp72D6CX8dkBKbzsL3L5ElB+8euwjS3nXfJ7m3XKx6iTy2PKl029iKE87yM9SLWRmQHxR7O1oF6ConEt6XxmvmY=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: nextcloud

