apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secret
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgBo4fPoilAGeS8nLZ0H6M1+kE6Y3kO1m10u5iMxSx72QUsKoBtMGHxwMm6W3ULIoeZMDuQidXzPZlIXZ176Ssks9GK6ddt3PbPDmOq2eGemLB7FPdkaBGO7tug1mszXyZ0ZTg2SNklLWBuXhXM8xGu+RyXnOLDhMHCfM+9bCKRYXM9K1RbMeL3SRMmpsMSmJSLDx4c2HxwKBkN2x8InkPoXVaYtHYhYaCSCMizRa4ncJrwjVFN2j5rUsE6BP5lH3bLDoGRZPya3JrErv7BxJciAda52bLf7OBW0f+gCZ5Vw1qQmgvTU4CnSS1b9TKuaCPZdFR1qEH5PlhUiu1ctp6ecITGJCVvbmf2x3gu5yyqclsj9z8PnwYYVYrbdrYVhQt0Yme4jZ2ht/Vqh8+85lp9Ix8cMYX6e1PytiI2bT2gkJSfY77L0Cy7Ce2BasvbZ1Unc1viENo/cDZYvfsN8+PLQJ3MCe4II4pqty4GnIc7/fPdhHC2h+KAoYMoDWlzgtiIwJ1p96aFST7XtTWAnSGnT+exFBqyte1DrtL5PS5EF12/NlGz0vWHkTofX9xCPdITCqcsDpADtU3zhZWTDDTz7lFg17bAAAGJMWdkUc2JNF+8sEBKKyXe+TRgjlRnFLtV/7Ymp/4ryF+e58CK0cZEA8F/0R/5DL8+51f0hsSwbMijkH2QlcSA/8yWWkzDNzPPLdZL34b/lq0XrawVOsg9sGCc0ELPGozpf20rbjTva2A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mariadb-secret
      namespace: nextcloud

