apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgCyW3Lesx2+IJXOrN0NQJqgRlqGCW2xmg4hstvN61wRdH2bLfkF+5wUiIkJ4iK4tnHmV5FCHN7YBK5sh9rj47In7Jj9BUonHybKRY3uOaozWrMrNwb1m884Wt1x4YHItSAEA0DT7lGapa4D3RJv/5s5vDTkajpvOcE7dLq9pjM/014nI5T3i3JRfHHi/jidNmWG5I8l6207QnYUnP2joqrzTKyBnEY60Ev0WAtQcreghtA3HIjOIHAdLX7W4Yankppx1yr+DBpO2gARHjeCOtuEkjT3+s4TKkl6in8RX18udEygY83DuzvRiU0Kty37yZmWG6o9DZiv3ku5vcTnrHekYtW1bzcqxQSaKIOFyp/Sgz1cjxG5iPrFAeav6TM8jVg3xa2jRkbVuhB9MG7Zavec8bj9OMnkKudi8WtHOj47ugTYuVmxDHdIu5N3qb2O/ez0aIOL/Wgs0VITCe3yP8BNkWO1TVW9cqb42zlEv5wjtArLpUnFzA/c38wP8pZLHXxNCXRuInQ2RNLyLYu24dSWP3FQBnB+6Ndv4nCz461Kv13ux2fqnf1spteiQ2GB6xkmThYbnDv5axxlCYGbLS0r0KBJ2UXbgeQkqAp770n1s+n3Sx+hdrHH27zwk7j8+EeT9rJQh1vM3feHxk1zR5aZKVKcdrkIL3LvKLTY5Q6K3XZjGY5oLW4Qpa1w9iOQI7ReN+YcZCr7uxgs1OTIiLEce1R8qS1OM5g2GAfEmKjLpg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud

