---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
  namespace: nextcloud
data:
  NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.codekernel.co.uk"
  MYSQL_HOST: "mariadb.nextcloud.svc.cluster.local"
  MYSQL_PORT: "3306"
  MYSQL_USER: "nextcloud"
  MYSQL_DATABASE: "nextcloud"
  REDIS_HOST: "redis.nextcloud.svc.cluster.local"
  REDIS_HOST_PORT: "6379"
  PHP_UPLOAD_LIMIT: "10G"
  TRUSTED_PROXIES: "10.42.0.0/16"
