apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgABYlkAnH4TLVkOpHO4h15V0XkQUAwtqcZLNlkejh7U/jJQv7ciXry6CU6/Pt8jaFiPul79ML34Tu+zdWZdUVNzL2B13V3o1krbyt+0XSdQwqSeqwlECmOM6zFbDd3GX9VvVM5HIbqFO+XEX+JgwkcKF9L8RSj+sljyXXOUi7RYR94Kuhx462lCZPiLvgd3DC075pcSysWh5GRmahE2U4V+MeH2GBCjg3wMcAHfvH4s57br5Pf/aYWgwi4GdBOhbpl2uiZ1vdBGS58SZ9d/PNSC6onO1Ogvn6/goI/hCfb1tUQkZaRi77subax4XOtakaqeFzvORf9rxD+eJk01oJ2EJyXBKFv7agdZNwXmMnnfdyWntWqmXL59lFS8MynpMVCzvvyckvtr1s0Nouk8v/Et8GbpgIqNX5KC9Zgb92ssQEbSqZlybnoWw98/VyoSmoCZ/DuHyxWFcRyISIdet7sIbXRY31E32yAHN5VjbBbSzyy0+cTqtDSiy70yuXIWCqhy11o+8Xjra8JuD7IeTFLpHmw80CPBrEqmWXmdWPf5H6Z/HGmL4RkfL+eJ1f12r1W535v+XuQSx1pYXUVsI9sxFoFNNXLfQIHDSau1jkTC2lDJp6b2Hy7HeABhuLQgrY9f1IiMSh//wB290Go3Icbp44e48L2hQZvD+popzKFWEW/jy8tWlSnbd2Kg/Mx6YO+j6/hqxfYBrYSCpW6IVBkYaXfdo9vO7LWTZWn9qXiXbA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud

