apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-secret
  namespace: nextcloud
spec:
  encryptedData:
    MYSQL_PASSWORD: AgA2EWWq67u22XH47wCmHvdINfGDl/kCqCD5rhHjH1agQ01eg5P6ao9P1J6PYwkEdMYVbLLShLbpHBpENwoM8d89vAPp65Cr6e/kb1EVsnVGbyTv9oDI0Th13ujvYG5IVKlZzLFFPjdegdnwpvPP2wOFfq4IJ8v/yOEaxDx3GqR6QuVGP15Rzih5AsGCk0F9PIj+rRFaOOtRksQpqxGW4naj2BmTfT7p5qS1a89Flu4cmddpjx2bHN1dFAwCHTVwtI+H/2giU+ATe8679NSLQNmee+R1i1kg4G1XFWvVbudXrFci0Kbg5VorY8ms+fWbCyRmb7dxnTZ1kfkOtFi2xKnh6N26hSZsJy9mFrYjOaVkT8u2Evbhu73cYvbFfouEZjmyrgc1WGb5HKV4qMg0NHqbqXW4shyieeF+CR0yFWs8Iz1fQtssP5FmmZKjfYjKQzlo7qykTXnbZt2tVphgRTO5gFXBWLal5RDdR/54kq0LA/fRozkXpziizhSD0CgnJyCDFgFX5+52jtPgZmENKGv1gqw1Ejf54dGb0uDi/zJQMuoSywCb1G65E9NpiiwRJN29SXrQPb0rAy7mpkqtWb2lG2KsdmxOyvNzGcksH8Qp+M+k9LpoyxcZ08PQU+cgduWiyfMXB/+YGGwkV3544gHP5dkTJF8tlRVjhAalCYpsOGT58lljgWAlsYEvUKL7bXyrD3d/A+M60dYUltfIw6AcveS/axiKtko=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-secret
      namespace: nextcloud

