---

- name: "Upgrade K3S version"
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - role: ../roles/upgrade_system
    - role: ../roles/k3s/b_download


- name: "Restart master node(s)"
  hosts: master
  become: true
  gather_facts: true
  roles:
    - role: ../roles/k3s/restart/master


- name: "Restart worker node(s)"
  hosts: node
  become: true
  gather_facts: true
  roles:
    - role: ../roles/k3s/restart/node