---

- name: "Bootstrap the watchmen"
  hosts: watchmen
  gather_facts: true
  become: true
  roles:
    - role: ../roles/upgrade_system
    - { role: ../roles/wireguard, is_server: true }
    - role: ../roles/digitalocean/do_spaces
    - role: geerlingguy.docker
    - role: ../roles/digitalocean/do_registry
    - role: ../roles/containers/jellyfin_music
    - role: ../roles/containers/restic_backup
