apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: gitea
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgC1O2Z02XM3gZsYdMCEiPEdJkGDXHjWeCJ+ruGIoQn9Ew6RZRpmIvX8VqSDYxogZlCZcflPzY5k2gK9TDdOyhVsscsaFqjlMLvwyGrpQzBTVt3gmSj/Ge6UmDhDmH0TCawEphvHFFTOImXvEyOAWxWKPlJVJZneq1D+Yof/pl0u/u9vELYhx9Zdo+OC/tvEANH6htHPjdrsQVfyymB1080+sq6SCq4w1EeatFg4WiKYGrTDC7uUoDnQ6m0lAyKKozvrPZzrRla3WxmiaGnHPEbdy+w8ou27kO8mhkrNIaynD9hl6AW6VsnH5ZakBawZjZ25frLLoICsSK/1wgpto9xbKezTVAAM/NDQMH/0QdsfqgEpQ/Tvudu8HRIMUqh/WralpDCuVQ3/d28lLoBHiypl5f+UuCGcC32zZGfYQzx49ihhd8jt8vEvVizaEMqCLQqmIp1Z8i3yxPxvoQyvk0+Yv329h/gr01aFXP2AYvwla9uo2Fs6A+rAcLTqCGB5WxyUQEUPvJdg0pK5713Kfkc3EIX4ujU8nXE8G2vOBlPxLY9S6ieEmjZFLzMEAwowZ3uavc0BxwgFgWJMDqUW8xfdUcCKkThDS8rz76FdzDBnlRg1Zj+dhYVPHg0hVTTUtZk4c3/YnrBS1R4TkfpBFi5CYrCWhK8tWxtfszcx6qu1MFIdFpBFmusfps3DmVzh2XHAfPYZdc3YeEQa+8SXcI85qELou3hvZJvxIHfsSYYLYw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: gitea

