apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: gitea
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCf91Gf3xFtrOJN7I4LVw0uNAalBorlkFpn6W6VFupAa29W7jiZSFDqVodlwktntjqoKcz32avh0POnlrWF36XTwfuL2DyJfK2uM+01w+yGLpcDhLjGwLW0tBJ28UWX+DqWrQwakm45jDxhIz8RSeSfW+/GBTfkdjhaY22wf5z9VWwKJ2sC/oqe8h/zBpY9BRXIZmWVGAJ41U4wIZQ1bG5CrwXLV9t6PvRua01ZA0gvq74FVYtw6Ive0PSz4Y7XT63qelJpjY2ecegcNRxOU35EmbSkvYZJ13TqPrnylcw8urnAavIsMq+d3fyFO090P9hV8ESAHKiANmAT3zoGj19xQFmUGymimyhT5TURDPGylKrtEiHWXVwZTKZn88GUfX2iIo7X9bjbYIuiMiTgcj6/x4HXg+VGov7zxeQwAc4HyAWNZ+Hxhhib5sOP5/TG7de4wyodHZ8UBsb23lgJzer/hiVFZNlFIqhMt3ifkDFVFqBigcSBJH4JScPW6uyjLKnYYOg0ahP0To6YxhqED8/CJAik61iLUgjQkZksiYwy5TWQNtSeE1wNU1Xyi6iFa3GPiidHjkLCamPQuZCQdYuLvRTa5HauOR93xWybNDQfawzxJxEZOLlZ4Zx2ATiviLbncWlBUefxnftNgjhPEV+0AohAmRyvF+KyIFksI9JMZ6KhDYb30xenU0q1k4+aMlVXLd19QHMIvqQGqCgYpfc3slvF8VMht96RsRHN8X2ITg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: gitea

