---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: gitea
  labels:
    app: postgres
data:
  POSTGRES_DB: gitea
  POSTGRES_USER: gitea
  PGDATA: /var/lib/postgresql/data/pgdata