---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: gitea
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBS6UQvuVzVAdy6RcAuWiDazBFDj/75mzvt0gn7ItCVl04GM/3A0eqdJ39daTN1zt/8Mzor+Qm5RCRH955RIS11HDG8ITwX7HydLidfY4WDAFlTlV8jqrnrjqfYoJw99chhGg3bQH18wQw2RGGvfd/vfswURIffUlGifvzHbeeUeZNNyD2KTKnBZE7VS+fXd95SsVY1zEqw1sKaaxV/qvy9t1pKxMEGtxn8zvQejM9A6hPGEtRpu9xZ78CcwhV56CGjL9ZpJQ27WsVRom/CKk9bsFt3ILBq1XlANYEkhVcylF2ClZxtm6ebQUADuJnDeTPyIH17B+5JzVjSK3nGdwXEyvisMcPQRuHpJuvvj6PM/9MYylh5zucijgiD8ciOg/amVi1uB+FXskz9DUKCEqU8kfczSTibGrbl1lQiPkObdqWTwBtVlHtjE2zEW44DF2FmnxaXA5leoDHqnOzHl64e1Sgqh+iUPsDRQvR0bM9Akf3dB5m3fjligfpuRs5+diLz7QI9oHEg5d4voFa+uEY76x+nKd6r+z6EsoY+oCeEIs2iJu7LYfMTCaqSD701ygSfHiokqhZXjJ56c3VOMHAzcS5xs0nM3WlagzkgTeR/SIjGTHfqWr+phkWW1Q4jMn0kSzssxQg47/JNhMWtHN2kNh234MqyQsFWN6Bew9qFpEZXssOHwAS/qz+BHk2od076nqOKQjnQ+0NuAueVRfaD81sG9w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: gitea