apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secret
  namespace: gitea
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCjrmDN3/e6YuYUH20VXk+2ilxDhQxaU9wT/iUVIvkiGopdj9tTwlZlRTB3UYMOGffP6k5Pjw2a1y88CTFhnHEPVENAam5N9taTxXvU2LYH1t+Og20q+CpggdkPFplnwUG2RVWA4UR2dO2V1mCEXY0RRh3miWnoSjEguYZXvqUE+muE7jvebpKdLUSCCu+NBGZ1PMbPY++mNZTnjlH7w9WrUXG1hQvzjZXXD2TQJCcptLFhYhHvoPTrblxMG5CKGl/CSSJOD86K8RVN159wOgTuuF6gWKM1ChXBDZ90vgJKEh4c0+vPKqUss82jaN3Riep44wUluQ6SutcbXx8fkGHxIXarV+MCl35TFPYP7rRePHcmzYfx7yyvCf6DX6KWjP5M/J1AjzaOMA0l0aUSPf9OX2AgC6USKWSdIuSb1Mjm/OcqaryQQ1iagDIazSArd6Je3WXYL9Zgv8FinsYz5iNGQYklkhsQMR2GPF7Ah5MNB0iUxTgr5XO6v4XdCHu7DgZS/HVlSs1QkQcMofou/eFnrS17pjXS0KBrROwN0aMEdE+T06WdrCsrJsyQO0ibQA/f75knsHLpu8xZdgGy/3utIss3DUj7vSmshyn3sCE82o825FqIUH7Ej1m+TyTHfpzWrQOJpMri0/I0dpWyTQ0jPD4sn8vU9NdiZFoRoY8vSqOoEWWvpRXTKWfed8qPZJD1irVYlGVxi1WWoSIm0w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-secret
      namespace: gitea

