apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgA6Wtm0PMY2ZZCW7uE2uWY4u1HRWNg3U3Zlc65uTK5ODA/2JjQgRfN7TlZN5hkxnWeRJ7fomRhNLZ1Gbt0gho8bE7JhkA8N8STXMC7RwfSP3Z/eVypO1y7DKlj03dLFV0AYZnPV5YgGU5g9lB7fHKZ2Ji882xdaAcqjAcVaFNTyYMs+eBTVSZFEwPR5qmpe7vgR5Uu+ZL5fabZarLFOfk0/CbHhayx6JKkJyr0HyfuYH4l++MQfDIEm12aXpwMi9Qky0JU3uSWebKR6WiiquqMm3zsKyht6UM4CIWSOjm8SYTms8r15EpRV0hDhvmKPXZOJMPvsCuhWryAbgsS/9YQ2QeWTsoqj/WsGBd2Mv++Kj/OaJpW157k4js2ZT0c0JnXWhx1pYmcWxfOU4jib+W229IjR8VQaxAkiLI8dD31ZwgBaFsdGFAEUnrPpdArS0gAbu3ThrDtwxyRGxYEGsTdQP4gnAAuEKu6Y6bPLIpOmtd2Yx9R7TrBDi8D5fGfQq4iDo9Sb73reuYKnoNbMJMtI8lDOMTFKvEDMf35cEiliVDIS5CiD2uNrInD1h1p9fMKnSmAPa6MhPMARI5sFRI+Jj41axcLqHpJAXAKPVABw3dm8iv2MnSDjFhNINyFqGx7LX43ESpporfHBm5H12CrbacWRgUJzn2mxMN5mzI18KS5ZxWHUew4j4v3xliLquqdzvJoaotMY5ZsuqYIYXHjadw2Yis4Gjuwn7taTFyd2zA==
    GITEA__security__SECRET_KEY: AgAgYYOS4bTjF/XB4u/pZgRzZykbOGr506YQRtslr5Bvm6YAWgv+GfDz18MwjUprymVVa6OQMiVwPyOpYQB8xgvY8U6/D++saK14HtU5GlMqEpylen6J8eQTG1bgyvw+fMwS6J2Bo70WzlascBRju+qjB52tsj1cuCBEc++s2bDnEEqhf6bqwAIZEXKR0AIMAQuNNRvJMl4Dfi7FXCewYgGJzUMS0ryG0nUTAEps5McJmHRfH3ygpdCki2BayvwTIMdkBySzuZx2bF5gPN1gGQT39fvkRF+AZyYAYZthrWMkD8tpPKBOqp7mLJswz8ppqQwBzp7P3EWEy8uaC8KiSk4SpI6vK/7r6J9zOiOwX4hOSu6JyckrT+0W2QASn6tJdxMbbOiZMNo4JjEhcNLRpZB1PpKomJQbuEWINRTHDX6gDT+P5CHzbNrmjCipnjlrnKeCOrJHKBpYlHLPWSLrjCUHcd1KXfYiR87iXL4CKx5gubsoilxgbyOKPBSb/pNTJoBS1Ri2jstoR3CJa/RHePC0BMq9p2o0GQQifqIqx6IvBvibZPloBA4zD4q2xivyvl+NGO565TQgiiJB/e0kFrB+vyXbzDHuiBI+A1xJOjUU2/xi2e6ASy6Ta3K9QinT1femAKJ5pG/DSqdB2xvWOPlt0YpC5RsWSqQC6YVuMIyuWxWXCmb7kwxowTnGSPuCVGwGa0EjKZevXpGxj9R7ZVfU9VLFKhzPQtglUBMhOW3Csw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea

