---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgCG3y5t9dJMTOIdieedSK1KvH+elu1zMBYBBr0HP7lXzN3zIO6JJMGDP6y+i3dINojxsACHpUbqOGWWS37AFLX3Dv6xuGZoj7txCE8iamqbj+sMsiHarhX+2AxwjlLw6urUgBoh8qfrLFkX9mT5EtSutaQYGB91ie85ScZi+CNY22npTwYDbYQu9z1Wa6c/JemTM9OY3ieppGuwfoqP4ag6yHemorGd9YYC9KOt2A8219Bs/TKRFm+XRV4ezjSzQLq86SPqUcniHGreT/T4Tx2YckbsqTQewmDTIKXhEf3ppxTZ+LYAiC1Ok6yvV3g6BgR0RehH2x5a1YwDf0LDlq/3vNhTLNlJwplY1Y/z/rYOxlfRJ63ZjIWszSq6T3oKNKPcr3hEsw3gL3RbFLp8Ft7JwfZjPW8a0ENUbjfOzWnnbSXeknYw5thic6N1u9qAywfoDjt+GaR9W+p7tlc4D41zEPrjeIxVKPreDDfYLhGtz7TyU11wxNNdsCnMc8U3StMdfHjeLz/tC9zQpIHmIAzxA4k+ovWMHqLrZA0QSppnaxC580j+L/1eYE+gv+eD93WXkiIgBYiQj6yKFCWWpgVBdcPEstCeJaJMXrT16z+scHCVJKzywFciQYY1/9rGbgzYg2tQuvpd6H8O7KFAtvmZ865nLLtus3snssJN0uLsXXgaXBUoLc445QPNCjrgjzw8SVHCF9ic65sACciY+R9u+1+hYA==
    GITEA__security__SECRET_KEY: AgBh9hrVfe5c9vJ4FyB9zAhAjyqR3yE8HCdN9zJ21cNCUO6trRlmS2Em9bB5wlN6WQSlJ8pX+12Nx8L0u6ajqeA1r9LgyssrEG0RdBVTHMJFPY/LkB6DHyQpijONU39jFzSDiDEhxjJAjevcEXAuTsdov91vQK7c8YiNe1kbMDqe2rgSZayuoj7sCWz6l2XVWX+9+SBnZ+cac20strKXGCSA1OqD7tG79O8CIKQuYZKGTDhnfoJzYTxWPWUV3+qN9ZPIrk7jBFO5dwqVWiViQ6t2GFSddgBritYXxuGrV6hZWoszEpaUnpPD59jxa5ogcZewWWxabf1RN0331PeT7kqdiKy1ngyd4HXHzcp+bsAQakHPxS2vOMt3luR5l4yBjWsQbwJAP5+xsZEHU2PC7egsSBwK/rtNZOPNzH/8oSQeWoTOYRe9FxrpPXV0d/thiHG6MDBD23I6sJKfkKdm8I8g/qFpoZphLEqgTVw6Fm+0mVl0bRfkqaSQCl0O6i+pq2omlpHba/lHN8Ts47Q88VY8dkkZSf/PekoyXAMTayW+boiOIUHk1XFaKKoMCKAlOBO7Zq32OKAZHbedE1yzvTTNxSvOqO4rjeoLkB+hPIo4KP9cGmsQkKnYm6beu14/uFg8MIBtk663AyE11D+F+CtrWb4Kl2EKrUheTrShC6YR9+BXrTkc6mBkHAYW7dhYpJb96QL0oIFSoVaPFQ9inF0raGC/x2MQO9oxN40ZQ6gO4vimJd1vWjZPOSeza0usx+cwd0E/s3xgCVMZFz3OrBaK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea