apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgBF6iHx1nd5npLN3PjcT0RMGGys447+j5D95yrb9nTsdUFIxXZGnB9GBPPDq1CKcYyad3stNMN6H6GC2/38TH6YVoVlyV00b54M8B61EB8uqhAcDfR7I82S3yBFX6WRbCXYv/oa2GqjwKpKXIYEM3KvbIVTnZSCMt/sq+yq41KE20T9VikvwVNtCf5pei+DR9pUNKHA1n5qpuENx09xTB/ws/xo2Us8VrXiVCBkKXudxq9Dr/8Hz6fR9K2nOxvaykBY2S4wM9CGWjHwwORpKAejHwvbQj7fBGmDEoVtChhFY4RWTTzVnYy1/c3AGdsmIF7dxxnxZzrzIGh9Fmpl0XdCBFDlb1zc1ZY9LWKkIu63oFpl6d4DweDrOB7B/+zhbbhaNwookJjmvtnLoqoLzBkGTni4FCSKWMLyhMwTvONbHts76RCMzZz4z284zYn+ogx0iDE4XQuECOqd1P9oWl8bgkGtJB2ZmbD7DpmslfzenbEOOHfODXrkMIwlzHuaDHI4gtmqHPTNORz5zwfDNOwJ8JWwaelZiP3sG6RVH0mIhiHGA/UumnQifzuQJdkv/0sQUQ/H6s0Iqd9Eb5gGRI00x68LVMiVJSIF8La/Ewz9o2uyfMYMft2G+4xqNlA48jryK06aGYjzn9Mb5QRXVCJuk9TLlwoFcmy+K6jymhdlewLwOVY6tYBftYh24+TouEHp/HqebKWGA69Bj3Za1w==
    GITEA__security__SECRET_KEY: AgDU00cW+zqoQLRI2E+Waj3z2Z/mfLc10Uov/V9Zb87FTp3X0e9ut+S54BHfeTgEFGV2ecY7wD7RnW2nfmcJOIqvRq1Mvu2asRxFjHCy2WKDSeaPVcrDl6oHPrRdwaZoZbMIe0w82PWLzKvLMULT95aoPHDtbNJsoiKCxNo04byJze5epfDykcOItrMChMLd7jjctb+DRD9L+VPJdxUEaqE21sBY12+ZRljLdcotGjLIqQWueNyS+qmSx3oZmPvv8rvUifnLhweEy7n4wLJgMDgo2IhVcORaz4jJKTDB378GPPPV/6L5tzxQBqnlpVC54PDW9O+y1EM3ZlQmTWpLrmTdfM4STlopM7BkRufLVxZHMRQ6ecM+ZDqI6rmP/KvA0CXaQXrDXRu230VqazA/qZ31my6eD+7/KfNPwJutlh1Q5uRJot14g4PNDwp7CONGbA7cSJplk/NYaQNbXkPCnelyI50nWkZNxOJSf+2cTzCPrkktzkN7oCR1Z2+QI5UgAf8kAninncMr2YjwVgKmBhDiaE2be3YbIgd3q/EqaadnA+Qq7O5cUds9R66+1VSveMnTMSPE5dZGaGoLGNI4YdpcEg+a5/xYiAOPNnFIY0UVhOTzfSSQJUGF9Ze0ljVQan3v1VGXX4h75XoAExP2wDU/1avNdety+Jg3RzPusDhU83RekUvjA8gg8YeXPJENoaPYkN+FCH9F4hIGMks0Pa5ugmlitJuUlSwXcO8Q6he7bA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea

