apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-secret
  namespace: gitea
spec:
  encryptedData:
    GITEA__database__PASSWD: AgA4ljr/AWerEbS6lToH15o332DlMLn//y7UOR282aDA/oJsm6GF+PMSYTvLgeOKPrLMCEqml5/y4kCXJTXHCcIkeG0jlo0utTP+WsEPgBzPiQ7S/LtaUKYwdw4jhWN2UWMrKxR8yeft5IbLubePNyckMHXQr5SmyFPnp5C2DxX+QRW/6WqFYGlMwhGJTyWD3H0t1ySnRlBDHvVfeOsMw/J4TRlfp2gTGOCLL6w5QwQt8/sxChsFL/dKPognr/UJ4sYaoE7n06VjGhl1/fbWZktagNKNz82sXT21po5hiPt9QQRr6D3NNrBthXal+odUmej9UYq6W5CQEzLk1w4VQC5j1+NjOK1tp6AhKg7N+htdchohxLzoAYjX2b+oJJb0QQOMH5ZRctoQZl3ufFUNbhzypeI99i+GDj5c72Q48iCSAK4vhp86nVZ/LBpShcGLIrckM2bZM/ThILxMgW11R8+TZwcCCUliS5TBIf6IbpVvS8UyB1Ln/wnO2+HDXf7V34cksqP38gnkNWeaib4C5YRdgDhD8R/lp5bcJF05Ntxd8n+MT3y4pcseQGd+X+zff5Vbwe3DWikSLkie7kOWx2omhpwUzJiBHaNQyKhLBDlvPRJ3KsLSAqlNYi2rYuYBnkgRAgjINndCMyRDJgZ08FzXt9xoRAaQMr8bAoBYYzOdxnpmHSZmxRZD9p/7uZxUJBh/nQ0X+gcqBYihO36xlcHzhuHj5QyWLWolmfqsl5uMiA==
    GITEA__security__SECRET_KEY: AgAiwCLuyDu+OIZqMcafNMsZX+g1W5SM5HmkqwFhN22CH7TbbpxFabybOue3wq1CG7nmSBMRWf5WziNDWtieYG9w2e1gG2wJ146NYfNZ7TiA0F1/KH6ff+xIQY5cJ/HwOERtUzeqKfsm2XQZi1qp0ZSXsBKeE3mvMGFJHMS4wKHTgcNhiOioPnqDgEJkilxHk7PV9MNndtN1LJg+9JsyGRmqE/qT8S/lE4jxTgL62UbghrGmbhwtybM0+4n619sXUGlkh9HJfhm3qj1QAkFi6w6x9q0phIUqcxJi7tS2rxjcQtvBxEvfx9b0abFjZWwxXLZ9/cPlZAJCM4B1eGjA5wvzt7ENUhesDfT72ef66eAEH/IInCtFtq8tdZsM7kiNexTt7TDuoICiqd5B0vXlE2dE3ftfJYE29sTIqKDOP0NKbhagjMZvVX6lw5UdYakDDwFhBrQXon1xf1kUIOYNf3fFTS4QtXEKdh+gwP4ruiSkbFuh2phks4DQX6w/VEzctkAium/kHwPdEa4PfQUbtfKlHHh8ZgiefRqVqV6dRA83M7EDCUNIW1KmKF1V3afG92XBV1t9mJlaOZaB5Wu4RWTXSsn6ojVha5Tifk0TwVGi9E5GYD6Xe7V6Mmz+WSAB8i47CFMZ36EA1mSsJS/w0AyBu1Nhl5f8G+FOEqgeMf3jyju6pVMrYwhNDTchcn/BOhvz/b4OqfbtsmfRqt7IJziDATp7/yjyX8QLaEEDld1n7g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-secret
      namespace: gitea

